language: go
sudo: false
git:
  depth: 2

go:
  - "1.10.x"
  - master


jobs:
  exclude:
    - go: master
      if: ${TRAVIS_BRANCH} != master
      

# ------------------------------------
# definition for the build starts her:
# ------------------------------------
before_script:
  - go get -t ./...
# https://github.com/golangci/golangci-lint

script:
  - echo "current branch ${TRAVIS_BRANCH}"
  - make test

after_success:
  - echo "Jeh, I am done ... ;-)"
after_failure:
  - echo ":-( :-( :-( :-( :-("
