language: go
sudo: false

matrix:
  include:
    - go: 1.9.x
    - os: linux
      go: 1.10.x
    - os: osx
      go: 1.10.x

install:
  - # Skip
script:
  - go get -t ./...
  - go tool vet .
  - go test -race ./...