# doc: https://cloud.google.com/appengine/docs/standard/go/config/appref 
language: go
sudo: false
git:
  depth: 2

go:
  # gcloud run with g1.9, thats why test with 1.9
  - "1.9.x"
  - "1.10.x"
  # - master


#jobs:
#  exclude:
#    - 
#      if: branch != master
#      go: master

matrix:
  exclude:
    - go: "1.9.x"
      

# ------------------------------------
# definition for the build starts her:
# ------------------------------------
before_script:
  #- go get google.golang.org/api/pubsub/v1
  #- go get -u cloud.google.com/go/...
  - go get -t ./...
  # https://github.com/golangci/golangci-lint
  #- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  #- echo "current branch ${TRAVIS_BRANCH}"
  - make test

after_success:
  - echo "Jeh, I am done ... ;-)"
after_failure:
  - echo ":-( :-( :-( :-( :-("
