language: go
sudo: false
git:
  depth: 2

go:
  - "1.10.x"
  - master

jobs:
  include:
    - go: "1.10.x"
      if: branch = master
    - go: "1.10.x"
      if: NOT branch = master
    - go: master
      if: branch = master
      

# ------------------------------------
# definition for the build starts her:
# ------------------------------------
before_script:
  - go get -t ./...
# https://github.com/golangci/golangci-lint

script:
  - make test

after_success:
  - echo "Jeh, I am done ... ;-)"
after_failure:
  - echo ":-( :-( :-( :-( :-("
